name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build on ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: ubuntu-24.04-arm
            rid: linux-arm64
          - os: windows-latest
            rid: win-x64
          - os: windows-11-arm
            rid: win-arm64
          - os: macos-latest
            rid: osx-arm64
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
      DOTNET_NOLOGO: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # - name: install-dotnet
      #   uses: ./
      #   with:
      #     version: |
      #       10.0.x
      #       11.0.x

      - name: install-dotnet
        uses: WeihanLi/dotnet-install@v0.2.0
        with:
          version: 10.0.x

      - name: Display .NET info
        run: dotnet --info

      - name: Build
        run: dotnet build DotNetInstall.slnx

      - name: Test
        run: dotnet test DotNetInstall.slnx --no-build
